### ISSUE TITLE
SVG Style when using wsvg

### ISSUE THREAD

**Issue by rubychilds** [mathandy/svgpathtools#1]
Apologies if this is not an issue and the way I'm doing it. I'm writing to an svg file using wsvg but it doesn't retain the style. Instead it seems to default to black and the stroke vanishes. When I add this style back in via illustrator then it works fine. Is there any way of keeping the style from when you read an svg to when you write it?

**Comment by mathandy** [comment]
Yes.  Here's an example how.

```
    from svgpathtools import svg2paths, wsvg
    paths, attributes = svg2paths('your_file.svg')
    wsvg(paths, attributes=attributes, filename='copy_of_your_file.svg')
```

_attributes_ here is a list storing a dictionary of attributes for each path.  
I hope that helps.

**Comment by rubychilds** [comment]
Thanks @mathandy this is exactly what I had done. But I'm using an SVG with a style heading:

```
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 787.2 784.4" style="enable-background:new 0 0 787.2 784.4;" xml:space="preserve">
<style type="text/css">
	.st0{fill:none;stroke:#000000;stroke-width:0.25;stroke-miterlimit:10;}
</style>
```

and this does not come through when doing `wsvg(paths, attributes=attributes, filename='copy_of_your_file.svg')`

For it to do this, I'd almost expect an additional parameter: `wsvg(paths, style=style, attributes=attributes, filename='copy_of_your_file.svg')`

**Comment by mathandy** [comment]
Ah, ok, gotcha. Yeah, this a limitation of the package right now.  
More generally, the significant limitation I see is that the package isn't set up to _edit_ path elements in an svg that contains other elements (w/ out some manual copy/paste procedure being involved).

If you have a fix, please feel welcome to submit it.

**Comment by mathandy** [comment]
@rubychilds I realized this was pretty easy to implement (and a nice feature), so you got your wish.

```
from svgpathtools import svg2paths2, wsvg
paths, attributes, svg_attributes = svg2paths2('your_file.svg')
wsvg(paths, attributes=attributes, svg_attributes=svg_attributes, filename='copy_of_your_file.svg')
```

Does that solution work for you?

**Comment by rubychilds** [comment]
Its works well @mathandy Apologies as I didn't realise this wasn't implemented - I would have helped out and done a PR if I had known. Thanks for your time :)

**Comment by laurenzse** [comment]
Hi @mathandy and @rubychilds, I'm facing the same problem as described in rubychild's initial post. However, the proposed solution does not work. 

While the `<svg> `tag of the original file is accessible in the `svg_attributes` dict, the `<style>` tag (which is outside of the `<svg>` tag) is ignored. It looks like the `svg2paths` method looks only for the `<svg>` tag:

```
if return_svg_attributes:
        svg_attributes = dom2dict(doc.getElementsByTagName('svg')[0])
        doc.unlink()
        path_list = [parse_path(d) for d in d_strings]
        return path_list, attribute_dictionary_list, svg_attributes
```

Is this intentional? And is there any way to also read and write the `<style>` tag?

**Comment by mathandy** [comment]
`svg2paths` was meant written for a more specific use case, really just self contained svg files with some conditions at that. 
 
The newer [document.py ](https://github.com/mathandy/svgpathtools/blob/master/svgpathtools/document.py) IO functionality is meant for more general handling of XML docs.  The idea being to give a way to edit path elements inside an XML document.  It has some limitations too, but may work for your case.
