### ISSUE TITLE
source code installed through pip does not seem to correspond to the source code in github

### ISSUE THREAD

**Issue by piscvau** [mathandy/svgpathtools#108]
I have installed svgpathtools with pip and the source code I see for paths2svg does not seem to correspond to the source code in github. I am looking to dimensions section after assert paths nodes

**Comment by piscvau** [comment]
and unfortunately the pip version (older?) seems not to work with dimensions and/or stoke_widths = 0. Being not an experienced python programmer, I do not think I can help even though I would be willing to do it.

**Comment by yig** [comment]
Use `pip install --no-binary :all: svgpathtools`. The binary wheel is broken.

**Comment by mathandy** [comment]
This should be fixed now.
