### ISSUE TITLE
How can one use fill attribute with wsvg or disvg?

### ISSUE THREAD

**Issue by p3t3r67x0** [mathandy/svgpathtools#109]
First of all thank you for providing such great library! I wonder if one can use the `fill` attribute with wsvg or disvg? I saw that you have set the `fill` attribute to `none` in `paths2svg.py`. Is this the intended behavior, or would it be possible to include the `fill` attribute in the list of parameters? Do you want me to open a PR?

While trying to use the fill attribute..

```python
wsvg() got an unexpected keyword argument 'fill'
```

**Comment by mathandy** [comment]
@p3t3r67x0 I'm not sure what the expected behavior is here, but this appears to work:
```
from svgpathtools import *
path = Path(Line(0,1+1j), Line(1+1j,2+1j))
disvg([path], ['red'], attributes=[{'fill':'green'}])
```
I'm closing this for now, but please re-open if there is a bug I'm not seeing (please include a code snippet I can paste into my terminal to see the problem).
