### ISSUE TITLE
New Release Plans?

### ISSUE THREAD

**Issue by jingo64** [mathandy/svgpathtools#117]
Hi!

Love the library - we'd like to use some of the functionality added more recently, but the latest PyPI release/project tag is over 2 years old. Any plans to push an update to bring the new work to the masses? 😄 

Thanks!

**Comment by abey79** [comment]
Seconded.

@mathandy Any plans to push 0.4 to PyPI soon? I'm preparing the first release of my project and I would like to avoid vendoring svgpathtools if possible.

**Comment by mathandy** [comment]
The version on PyPI is now up to date.  Sorry for the wait -- I had to make some changes to the readme to pass twine's new checks (in the end I just converted the readme to markdown which satisfied twine).
Anyways, thank you for bringing this up and I do plan to update more often in the future.
