### ISSUE TITLE
Line method intersect does not return the intersection point between a vertical line and a horizontal line

### ISSUE THREAD

**Issue by piscvau** [mathandy/svgpathtools#122]
It appears that the line.intersect method does not detect the intersection between an horizontal line and a vertical line if the intersection is at the end of the line.

**Comment by mathandy** [comment]
Hi @piscvau can you give a reproducible example please?
(i.e. some code I can paste into the terminal)
Also, just to say it, thanks for your all your help with the library!

I'm closing this but please re-open it when/if you add an example.
