### ISSUE TITLE
colors are not taken into account in wsvg if path parameter is an instance of Path

### ISSUE THREAD

**Issue by piscvau** [mathandy/svgpathtools#125]
Line 207 in paths2svg : 
if isinstance(paths, Path) or is_path_segment(paths):
        paths = [paths]
 if a path is submitted with a list of colors why embed path in a list again.

I would propose the following correction: replace line 207 with
if is_path_segment(paths) :

**Comment by mathandy** [comment]
@piscvau I'm not following, can you give me an example?

E.g. I thought your were saying the following wouldn't work, but it does afaik
```
from svgpathtools import *
path = Path(Line(0,1+1j), Line(1+1j,2+1j))
disvg(path, 'r')
```

I'm closing this, but feel free to reopen if I've misunderstood.
