### ISSUE TITLE
Python IO streams (io.IOBase) support for SVG data reading and writing

### ISSUE THREAD

**Issue by pinkeen** [mathandy/svgpathtools#138]
Right now relevant functions support only a file path string arguments which is quite limiting.

Certain use-cases require that data is piped via **stdio** and it would be very convenient to provide this option for  **CLI** tools using _svgpathtools_. There are some cases where it's preferable to juggle raw SVG data strings in memory. Currently the above can only be achieved by using temporary disk files - this is quite inelegant and inefficient.

It should be fairly easy to implement this transparently by checking if argument is of type `str` or `io.TextIOBase`. This would also allow using `io.StringIO` for juggling in-memory strings or custom streams.

**Comment by mathandy** [comment]
Closing as this is I believe this is fixed by #176
