### ISSUE TITLE
Split path at turning point

### ISSUE THREAD

**Issue by jindili** [mathandy/svgpathtools#153]
Hi, I have a path triangle like path like this：
![image](https://user-images.githubusercontent.com/73845/125943480-90f0a633-178b-402d-9b45-58d4e15725f7.png)

And I need to split this path into three parts at turning point P1, P2, P3

```python
paths, attributes = svg2paths('tmp_svg_3.svg')
list_x = []
list_y = []

for path in paths:
    for pathele in path:
        pstart = pathele.start
        pend = pathele.end
        list_x.append(pstart.real)
        list_x.append(pend.real)
        list_y.append(pstart.imag)
        list_y.append(pend.imag)

print("X Min: ", min(list_x))
print("X Max: ", max(list_x))
print("Y Min: ", min(list_y))
print("Y Max: ", max(list_y))
```

Now I can find the Min, Max value from all start, end points,  And need some help to go further.

Here is the svg file used:
[tmp_svg_3.zip](https://github.com/mathandy/svgpathtools/files/6830438/tmp_svg_3.zip)

**Comment by mathandy** [comment]
Looks like you could just check the unit_tangent vector just before and just after each segment endpoint to look for big changes.

**Comment by jindili** [comment]
Thanks @mathandy, it works,
```python
Limit_Delta = 0.5
Delta = abs(cmath.phase(pathele.unit_tangent(0)) - lastPhase)
if Delta > Limit_Delta:
      print("Turning Here")
```

**Comment by mathandy** [comment]
Great! Glad I could help @jindili
