### ISSUE TITLE
Make Path Objects Hashable

### ISSUE THREAD

**Issue by matmill5** [mathandy/svgpathtools#154]
It would be nice if Path objects were hashable.

Something like this:
# Hashable Path
    def __hash__(self):
        return hash((self._start, self._length, self._lengths, self._segments, self._end, self.meta, self._closed))

    # Comparable
    def __cmp__(self):
        # TODO

**Comment by mathandy** [comment]
Yeah, agreed.  
Path segments (Line, QuadraticBezier, CubicBezier, and Arc) are very hashable.  
E.g. 
```python
def __hash__(self):
    hash(self.bpoints())
```
would work for path segments.

The case of Path itself is a bit more complicated due to the general-purpose 
def __hash__(self):
    return hash(tuple())

**Comment by mathandy** [comment]
@matmill5 I pushed this solution to the [hashable-paths branch](https://github.com/mathandy/svgpathtools/tree/hashable-paths).

If it doesn't work for your use case, then please let me know and we can adjust it before I merge it in.

**Comment by matmill5** [comment]
@mathandy Thank you, I appreciate it, this looks like it will work for my use case.

**Comment by matmill5** [comment]
Issue resolved - closing ticket.
