### ISSUE TITLE
Add tooltips and hyperlinks

### ISSUE THREAD

**Issue by TrevorGrout-NOAA** [mathandy/svgpathtools#157]
If I wanted to add a tooltip or a hyperlink, how would I accomplish this?

**Comment by mathandy** [comment]
Hi @TrevorGrout-NOAA, I unlocked the wiki, you can post it there.  Is that what you were looking for?

[https://github.com/mathandy/svgpathtools/wiki](https://github.com/mathandy/svgpathtools/wiki)

**Comment by mathandy** [comment]
The `wsvg()` function has some basic functionality for inserting text, see the `text`, `text_path`, and `font_size` arguments.   You could also use the (not so well documented) `Document` class for a more robust solution.
