### ISSUE TITLE
Add install requirements

### ISSUE THREAD

**Issue by tu500** [mathandy/svgpathtools#19]
Is there a reason the `install_requires` line in `setup.py` is commented out? Uncommenting this would make pip automatically install dependencies.

**Comment by Cabalist** [comment]
Not an expert but the `requires=['numpy', 'svgwrite'],` line below it seems to take care of that issue?

**Comment by tu500** [comment]
I'm not completely sure but it seems that keyword comes from the distutil code and is actually ignored by pip, but there is not really any documentation about it. The documentation that exists says to use `install_requires` and I'm not aware of any other python project that does otherwise.

**Comment by Cabalist** [comment]
Hmm...  You are right!  My Pycharm environment recognized the requirements just fine but `pip install svgpathtools` doesn't pull in those requirements.

**Comment by mathandy** [comment]
Hi @tu500 and @Cabalist 
`svgpathtools` is quite impaired without `NumPy`, and cannot output SVG files without `svgwrite`, but it contains useful functionality that still functions if neither of these packages are available.

If I thought that were a particularly good argument though, the commented out `install_requires` line wouldn't be there.
I'll leave this issue open for now to encourage discussion.

**Comment by Cabalist** [comment]
Hey @mathandy 

Thanks for replying!  I'm enjoying the library so far.  Made splitting up some paths very easy!

A quick look through the code and it seems like the only python file that would load without these dependencies is `misctools.py`.  I don't have the familiarity with it that you have but this seems to be 3 important but short one liners.  99% of the code has the dependencies on `numpy` or `svgwrite` and will error out with missing dependencies without them.

**Comment by mathandy** [comment]
@Cabalist Haha, well I guess I think `misctools.py` does have some "useful functionality" :)

I'm not opposed to this change though.  It's a small amount of work (mostly editing the README).

**Comment by Cabalist** [comment]
@mathandy 😄

**Comment by jean** [comment]
Sounds like at least the package should be using `extras_require` ([ref](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies)).

**Comment by mathandy** [comment]
OK, I uncommented the install_requires line.  I'll update the version on PyPI soon.
