### ISSUE TITLE
Is `svgpathtools` officially dead?

### ISSUE THREAD

**Issue by leycec** [mathandy/svgpathtools#195]
Because... it kinda seems like `svgpathtools` is officially dead. [The last commit to the `master` branch was nearly nine months ago](https://github.com/mathandy/svgpathtools/commits/master). [A litany of installation and runtime issues remain unresolved](https://github.com/mathandy/svgpathtools/issues). It isn't necessarily looking good, is it?

But thanks for the many long years of tireless volunteerism, @mathandy! Open-source can be exhausting, demoralizing, and debilitating at the best of times – and *The Colbert Report* tells me these are not those times. Wherever `svgpathtools` goes next, <sup>*...if indeed it goes anywhere*</sup> I'll always remember it fondly with nostalgic tears in my eyes. :cry:

**Comment by mathandy** [comment]
I wouldn't call it dead by any means.  I try to keep it maintained (working on new and old systems) and merge nice PRs when they come along.  
That said, I get your point -- I often don't respond to issues I don't immediately recognize as critical.  To as large an extent as possible, I rely on the community to keep this project going and keep developing it.  If you ever want to talk about a potential pull request, I'll be all ears.
