### ISSUE TITLE
bpoints2bezier() does not always return a value

### ISSUE THREAD

**Issue by vasarhelyi** [mathandy/svgpathtools#204]
This function in path.py might return None if order is not in [1, 2, 3]. Would be better to raise a ValueError or return something explicit instead.

**Comment by mathandy** [comment]
It does -- the `assert len(bpoints) in {2, 3, 4}` raises an error in exactly that case unless I'm missing something.

```python
def bpoints2bezier(bpoints):
    """Converts a list of length 2, 3, or 4 to a CubicBezier, QuadraticBezier,
    or Line object, respectively.
    See also: poly2bez."""
    order = len(bpoints) - 1
    if order == 3:
        return CubicBezier(*bpoints)
    elif order == 2:
        return QuadraticBezier(*bpoints)
    elif order == 1:
        return Line(*bpoints)
    else:
        assert len(bpoints) in {2, 3, 4}
```

I'm closing this issue, but please re-open if I've missed something.

**Comment by vasarhelyi** [comment]
OK sorry, you are right, good as it is...

**Comment by ntamas** [comment]
Note that all `assert` statements are ignored / removed by Python when it is run with optimizations (i.e. `python -O`). I think assertions are also removed when compiling Python bytecode with optimization level 2, so in general you should not use `assert` if you want this error to show up for all users no matter how their environment is set up.
