### ISSUE TITLE
Path.point() might not return a value due to numerical errors

### ISSUE THREAD

**Issue by vasarhelyi** [mathandy/svgpathtools#205]
This function does not return a value at its end, but it can happen that `pos` is close to 1 (e.g. 0.9999999999999) and due to some numerical errors the for loop does not return anything. There is no return value after the loop and thus None is returned instead of e.g. `self._segments[-1].point(1)`

**Comment by mathandy** [comment]
Yes, that's no good.  Thanks @vasarhelyi !
Fix in-bound.

**Comment by mathandy** [comment]
Fixed in 1.6.1
