### ISSUE TITLE
Rect not closed as output

### ISSUE THREAD

**Issue by sensor56** [mathandy/svgpathtools#24]
Hi, 

Thanks for your good library ! 

An SVG file contain a simple rect. If i open this SVG file with a rect (=closed) with : 
paths,attribute=spt.svg2paths('test.svg')

I obtain : 
paths
Out[14]: 
[Path(Line(start=(28.571428299+29.5050621033j), end=(325.714281082+29.5050621033j)),
      Line(start=(325.714281082+29.5050621033j), end=(325.714281082+280.933635711j)),
      Line(start=(325.714281082+280.933635711j), end=(28.571428299+280.933635711j)),
      Line(start=(28.571428299+280.933635711j), end=(28.571428299+29.5050621033j)))]

And now, if I display the d string, I obtain : 
paths[0].d()
Out[15]: 'M 28.571428299,29.5050621033 L 325.714281082,29.5050621033 L 325.714281082,280.933635711 L 28.571428299,280.933635711 L 28.571428299,29.5050621033'

And internally : 
paths[0].isclosed()
Out[11]: True

But when I open the file with : 
spt.disvg(paths)

It's logically open (see d), not closed. I think the d attribute should be : 
'M 28.571428299,29.5050621033 L 325.714281082,29.5050621033 L 325.714281082,280.933635711 L 28.571428299,280.933635711 Z'

The problem seem exist with circle so. 

I think Z should be added to d field when path is closest : isn't it ? 

Xavier HINAULT
France

**Comment by sensor56** [comment]
Solved by adding : 

            if p.isclosed(): # to close path in ouput SVG - add by XH
                ps=ps+" Z" 

in paths2svg.py - line 297

**Comment by mathandy** [comment]
Hi @sensor56, check out the `use_closed_attrib` parameter of the `Path.d()` method.

**Comment by sensor56** [comment]
Hi Andy, 

OK, so it'sn't necessary to use my suggest but it's necessary to change disvg() code with : 

    # add paths
    if paths:
        for i, p in enumerate(paths):
            if isinstance(p, Path):
                ps = p.d(**use_closed_attrib=True**)
            elif is_path_segment(p):
                ps = Path(p).d(**use_closed_attrib=True**)
            else:  # assume this path, p, was input as a Path d-string
                ps = p

Isn't it ? 

Xavier
