### ISSUE TITLE
Reason for using complex numbers to store coordinates

### ISSUE THREAD

**Issue by DomAmato** [mathandy/svgpathtools#29]
I am not sure this is an issue exactly but is there a reason complex numbers are used to store the coordinates of points? It would make sense if it was converted to polar coordinates but unless I am misunderstanding things, it is using Cartesian and the real number is the X and the imaginary is the Y. 

I think this is a holdover from the adaptation from the svg.path but I wanted to do some more work concerning the points and found it easier to just replace the complex numbers with a simple point class that has some convenience functions. My fork: https://github.com/brinnLabs/svgpathtools

**Comment by mathandy** [comment]
Hi @DomAmato, I appreciate your opinion.  Personally, I (usually) find coding with complex numbers, as opposed to real 2-vectors, preferable.

**Comment by DomAmato** [comment]
That's fine I was curious about it more from a functional standpoint and looking back over the documentation (https://docs.python.org/2/library/cmath.html?highlight=complex) it even talks about swapping between polar and Cartesian coordinates. For my own needs I think the point class has more use but I was more double checking that there wasn't some reason for using complex numbers that I wasn't seeing when computing the paths etc.
