### ISSUE TITLE
Bezier curve inflection points

### ISSUE THREAD

**Issue by 0x1af** [mathandy/svgpathtools#39]
Hi,

First of all, thank you for the svgpathtools.
It has saved me lots of time.

Really just a small issue.
I did not see a convenient way to obtain the inflection points of a bezier curve.
@mathandy, Would you accept a contribution for that?

All the best,
olaf

**Comment by mathandy** [comment]
If you want to find where the second derivative is zero, one way would be:

```
import numpy as np
c = CubicBezier(0,1+2j, 2-j, 1)
np.roots(c.poly().deriv(2))
```
