### ISSUE TITLE
Typo: joins_smoothl_with in path.py

### ISSUE THREAD

**Issue by pierslawrence** [mathandy/svgpathtools#44]
I encountered a small typo in path.py when computing the curvature of a closed curve. The issue is caused by the following line:
https://github.com/mathandy/svgpathtools/blob/bf95944c49e82baa13a0a9ff36d00b40693f8c11/svgpathtools/path.py#L2063

changing this to joins_smoothly_with rectifies the problem.

**Comment by mathandy** [comment]
Wow, embarrassing :)
thanks!
