### ISSUE TITLE
render svg inlined in IPython notebook

### ISSUE THREAD

**Issue by jf---** [mathandy/svgpathtools#46]
Its really handy being able to render a `Path` inlined in IPython notebook
PR following shortly...

**Comment by mathandy** [comment]
That'd be great -- it's been a while so I'm closing this issue.  Feel free to make a pull request or add any info if you like.

**Comment by vtrubets** [comment]
It's a hack, but I've been using the following:

```
import svgpathtools as spt
import tempfile, os
from IPython.display import SVG, display

paths, attributes = spt.svg2paths('test.svg')
with tempfile.TemporaryDirectory() as tmp_dir:
    tmp_svg = os.path.join(tmp_dir, 'display.svg')
    spt.wsvg(paths, filename = tmp_svg)
    display(SVG(tmp_svg))
```
