### ISSUE TITLE
polyline2pathd(): Conversion from polyline could not handle strings with multiple spaces.

### ISSUE THREAD

**Issue by ctc53** [mathandy/svgpathtools#47]
Said there is a string in SVG:<b> \<polyline points="10,&nbsp;&nbsp;20 30,40"/\></b>  #two spaces before 20
polyline2pathd() would return the conversion as u'M10 L20L30 40' rather than u'M10 20L30 40'.

**Comment by DmitryMilk** [comment]
Furthermore, polyline2pathd and polygon2pathd are not compliant with EBNF-specification of attribute 'points' in ‘polyline’ and ‘polygon’ elements:

https://www.w3.org/TR/SVG11/shapes.html#PointsBNF

According to this specification, all the cases listed below are valid and equivalent to "10,20 30,40":

- "10,20,30,40" (pairs also can be delimited by comma. Violation of this case I encountered with)
- "10 20&nbsp;&nbsp;&nbsp;,&nbsp;&nbsp;&nbsp;30 ,
40" (any number of whitespaces/tabulations/LFs/CRs allowed  around optional comma)
- "10-20 300e-1-4000E-2" (negative Y can follows immediately after X. Exponential form of floating point must be taken in account and processed properly)
