### ISSUE TITLE
Functions for converting other SVG primitives to paths not importable

### ISSUE THREAD

**Issue by warrd** [mathandy/svgpathtools#59]
We need the functionality used in the primitive conversion functions: `ellipse2pathd`, `polyline2pathd`, `polygon2pathd` and `rect2pathd`

Unfortunately, as `svgpathtools.__init__` exposes a function with the same name as the module `svg2paths`, importing these externally is not possible.

Would it be possible to allow these to be importable? I am happy to do any refactoring required if this is a change you would accept. At the moment we have the code copy / pasted in our repo, and would be nicer to avoid this duplication.

**Comment by mathandy** [comment]
I renamed `svg2path.py` to `svg_to_paths.py` -- maybe it's a bit aesthetically displeasing that there's now a `paths2svg.py` and an `svg_to_paths.py`, but it seems like the most practical fix.

Thanks for mentioning this @warrd !
