### ISSUE TITLE
Convert SVG to list of lines and arcs

### ISSUE THREAD

**Issue by Harvie** [mathandy/svgpathtools#61]
Hello, i am working on SVG to g-code convertor for bCNC and i need way to subdivide the SVG to list of paths made just from LINEs and ARCs. Because g-code does not support anything else except lines and arcs. Is there way to do this using your library? That would mean to approximate and replace both Bezier types using lines (or arcs).

**Comment by SebKuzminsky** [comment]
The LinuxCNC G-code dialect supports [cubic](http://linuxcnc.org/docs/devel/html/gcode/g-code.html#gcode:g5) and [quadratic](http://linuxcnc.org/docs/devel/html/gcode/g-code.html#gcode:g5.1) splines, as well as [non-uniform rational b-splines](http://linuxcnc.org/docs/devel/html/gcode/g-code.html#gcode:g5.2-g5.3).

That said, if you want to convert SVG splines to lines, code like [this](https://github.com/SebKuzminsky/svg2gcode/blob/master/gcoder.py#L507) will do that.

And, if you want to convert an SVG path to G-code, the https://github.com/SebKuzminsky/svg2gcode/ tool will do that (based on svgpathtools).  :-)

**Comment by SebKuzminsky** [comment]
[svg2gcode](https://github.com/sebkuzminsky/svg2gcode) does linear approximation of splines, and of elliptic arcs, which are also not supported by G-code: https://github.com/SebKuzminsky/svg2gcode/blob/master/gcoder.py#L760

**Comment by Harvie** [comment]
That would be great, because both bCNC and GRBL only understand G0, G1, G2 and G3... I'll try it.

**Comment by SebKuzminsky** [comment]
I'll be happy to dual-license the code.  Please open a detailed issue in https://github.com/SebKuzminsky/svg2gcode and I'll try to get to it next week.

**Comment by mathandy** [comment]
@Harvie you could convert to lines pretty simply

See [compute-many-points-quickly-using-numpy-arrays.py](https://github.com/mathandy/svgpathtools/blob/master/examples/compute-many-points-quickly-using-numpy-arrays.py)

You could also use the inverse arclength method `ilength()`.  To make a more robust or faster method, you'd probably want to go about finding the max curvature -- which might be a useful function to add.

A piecewise linear interpolation feature has been requested before.  It'd be a nice addition.   If you make a robust solution (e.g. something guaranteed to be within some controllable measure of accuracy), please contribute a pull-request.

**Comment by mathandy** [comment]
@Harvie  E.g. for a (probably overly) simple solution,

```
from svgpathtools import *
import numpy as np


def approximate_with_lines(curve, how_many_lines_to_use=1000):
	pts = [old_path.point(t) for t in np.linspace(0, 1, how_many_lines_to_use)]
	return Path(*[Line(pts[i-1], pts[i]) for i in range(1, len(pts))])

# test
old_path = Path(CubicBezier(0, 3+3j, 4j, 1+1j))
new_path_3 = approximate_with_lines(old_path, 3)  # using only 3 lines
new_path_5 = approximate_with_lines(old_path, 5)  # using 5 lines
new_path_10 = approximate_with_lines(old_path, 10)  # using 10 lines

disvg([old_path, new_path_3, new_path_5, new_path_10], 'bygr')
```
