### ISSUE TITLE
floating point compare error in last segment calculation

### ISSUE THREAD

**Issue by Shriinivas** [mathandy/svgpathtools#62]
Apparently the condition `if not (current_pos == start_pos)` in parse_path method of parser.py is causing an unnecessary segment to be added in some cases. Please try executing the code from the attached file. 

Maybe, the floats should be replaced by Decimal to avoid rounding errors like these.

[svgpathtoolstest.txt](https://github.com/mathandy/svgpathtools/files/2300313/svgpathtoolstest.txt)

**Comment by mathandy** [comment]
This is a hazard of using floats.  That said I think the performance benefits likely outweigh the inconveniences for most users.

Thanks for your suggestion :)
