### ISSUE TITLE
A function like disvg but returning a svgwrite.Drawing would be helpful.

### ISSUE THREAD

**Issue by tobltobs** [mathandy/svgpathtools#72]
It would be helpful if your great lib would offer a function which would not write to a .svg file, like the existing `disvg()`, but returning the `svgwrite.Drawing` object.
This way it would be possible to add additional stuff like `defs` to the Drawing. Or is there already a way to do this?

**Comment by mathandy** [comment]
Thanks for the good suggestion @tobltobs.  This is now possible using the `paths2Drawing` function.
