### ISSUE TITLE
intersection of a line and cubicbezier

### ISSUE THREAD

**Issue by derVedro** [mathandy/svgpathtools#9]
I found that there is an issue with intersection function. May be there is no issue but this code did something that I do not expect. So imagine there are 2 Paths and you want find out the intersection point.

```
from svgpathtools import *

# some shapes
A = Line(start=(0+200j), end=(300+200j))
B = CubicBezier(start=(50+150j), control1=(70+200j), control2=(120+250j), end=(200+300j))

# intersection points ((T1, seg1, t1), (T2, seg2, t2))
A_intersection = Path(A).intersect(B, justonemode=True)
B_intersection = Path(B).intersect(A, justonemode=True)

disvg([A,B], nodes=[A.point(A_intersection[0][0]), B.point(B_intersection[0][0])])
```
I except 2 nodes with approximately same coordinates, but they differs. May be using fixed indices at `A_intersection[0][0]` is not the best option to figure out the T value of the path. Let's see what is in` A_intersection` and `B_intersection`:

```
>>> A_intersection
((0.33333333333333331, Line(start=200j, end=(200+200j)), 0.33333333333333331),
 (0.40000000000000002,
  CubicBezier(start=(50+150j), control1=(70+200j), control2=(120+250j), end=(200+300j)),
  0.40000000000000002))
>>> B_intersection
((0.33333333333333331,
  CubicBezier(start=(50+150j), control1=(70+200j), control2=(120+250j), end=(200+300j)),
  0.33333333333333331),
 (0.40000000000000002, Line(start=200j, end=(200+200j)), 0.40000000000000002))
```

It looks for me like if you search for intersection of `Line` and `CubicBezier` and return values of `intersect()` on Line object have wrong positions. So you get something like _((T2, seg1, t2), (T1, seg2, t1))_

**Comment by mathandy** [comment]
This is a bug.  The fact that this bug exists (which was quite a surprise to me) has inspired me to add some `.intersect()` related unittests.  I'll push an update containing the fix soon.
Thanks for pointing it out.
