### ISSUE TITLE
Path drawing position bugs

### ISSUE THREAD

**Issue by Overdrivr** [mathandy/svgpathtools#93]
I am drawing contours, referenced from origin (0,0). Those objects have strictly positive coordinates.
However, when drawing them with wsvg, the following issues appear:

- Objects are oriented pointing downwards, with negative coordinates
- Objects are referenced from document origin (located at `(0, document_height)`), not global origin.

Is there a way to avoid this behavior that sound like a bug to me ?

EDIT:
From my experiments, it looks like document coordinate system is oriented y-down, while SVG coordinate system is y-up. Is it normal ?

**Comment by SebKuzminsky** [comment]
This is not an issue with svgpathtools, this is how SVG coordinates work.

SVG coordinate handling is fairly complicated, but by default the SVG origin is in the top left corner.  X increases to the right, and Y increases going down.

https://www.w3.org/TR/SVG2/coords.html#InitialCoordinateSystem

>  In stand-alone SVG documents and in SVG document fragments embedded (by reference or inline) within parent documents where the parent's layout is determined by CSS [CSS2], the initial viewport coordinate system (and therefore the initial user coordinate system) must have its origin at the top/left of the viewport, with the positive x-axis pointing towards the right, the positive y-axis pointing down

You can change the SVG coordinate system by setting the viewBox in the `svg_attributes` argument to `wsvg()`.

**Comment by vistuleB** [comment]
Maybe the OP is confused by the fact that Inkscape shows an upward y-coordinate system.

This is a known bug (if one can call it a bug) of Inkscape, that they've been promising to fix since forever, but whose fix is still [quite far off](http://wiki.inkscape.org/wiki/index.php/Roadmap#Inkscape_1.2_.7E_Refactoring). In any case, as SebKuzminsky says, SVG coordinates point downwards.

**Comment by Overdrivr** [comment]
Got it, thanks for the explanations ! I've been pulling my hairs for a few days while debugging things with Inkscape, turns out Inkscape is the one leading me into error.
