### ISSUE TITLE
Fails `paths-data-12-t.svg` from the SVG 1.1 test suite

### ISSUE THREAD

**Issue by abey79** [mathandy/svgpathtools#99]
I've randomly tested a few of the SVG 1.1 test suite and found at least one which fails: `W3C_SVG_11_TestSuite/svg/paths-data-12-t.svg`

**Expected result**:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/49431240/68542395-6ad7b080-03ac-11ea-90bf-5b26ee9c0b7e.png">

**Actual result**:

<img width="322" alt="image" src="https://user-images.githubusercontent.com/49431240/68542398-7925cc80-03ac-11ea-8fa4-6c898f28bb53.png">

**Script to reproduce**:

```python
import math

import numpy as np
from svgpathtools import svg2paths
import matplotlib.pyplot as plt

paths, _ = svg2paths(
    "W3C_SVG_11_TestSuite/svg/paths-data-12-t.svg", convert_rectangles_to_paths=False
)

quantization = 3

for elem in paths:
    step = int(math.ceil(elem.length() / quantization))
    coords = np.empty(step + 1, dtype=complex)
    coords[0] = elem.point(0)
    for i in range(step):
        coords[i + 1] = elem.point((i + 1) / step)

    plt.plot(np.real(coords), np.imag(coords), "-")

plt.axis("equal")
plt.gca().invert_yaxis()
plt.show()
```

You will need to download the SVG 1.1 test suite [here](https://www.w3.org/Graphics/SVG/Test/20110816/archives/W3C_SVG_11_TestSuite.tar.gz).

Someone with better knowledge of SVG and this code will likely identify the root cause rapidly based on the intent of the failing test:

```xml
 <!-- Test if S not preceeded by either C or S ,  first control point is coincident with the current point.-->
<path fill="none" stroke="black" stroke-width="3" d="M  100 250    S  200 200   200 250     300 300   300 250"/>
```

**Comment by tatarize** [comment]
My library passes.
```
>>> from svg.elements import *
>>> Path("M  100 250    S  200 200   200 250     300 300   300 250").d()
'M 100,250 S 200,200 200,250 S 300,300 300,250'
```

So does svg.path:
```
>>> from svg.path import *
>>> parser.parse_path("M  100 250    S  200 200   200 250     300 300   300 250").d()
'M 100,250 S 200,200 200,250 S 300,300 300,250'
```

The code seems to parse it correctly. But, maybe it has an issue plotting it.

```
>>> path = Path("M  100 250    S  200 200   200 250     300 300   300 250")
>>> Polyline([path.point(s/1000.0) for s in range(0,1001)]).d()
```
![brokenpath](https://user-images.githubusercontent.com/3302478/69314922-394fb800-0bea-11ea-9a51-f8321a3caeac.png)


That's actually correct.

Maybe it's actually specific to svgpathtools since it branched from a much earlier version of `svg.path`
```
>>> parser.parse_path("M  100 250    S  200 200   200 250     300 300   300 250").d()
'M 100.0,250.0 C 100.0,250.0 200.0,200.0 200.0,250.0 C 200.0,250.0 300.0,300.0 300.0,250.0'

```
Ooof! **Confirmed**. The second C there has a control1 point of 200,250. But, that's coincident with the current point. At the second command the correct method is to a reflection of the previous control point. Which would be 200,200 reflected across 200,250, which is categorically not 200,250.  This older versions of paths doesn't include Move as a PathSegment so it can't know that it's a smooth point and do the first S, but it *should* do the second S. But, incorrectly processes.

**Comment by tatarize** [comment]
This is actually the same issue found in regebro/svg.path#17

The correction is also the same.

Always set the command.

**Comment by tatarize** [comment]
The trick is last command is still stuck as "M" for the move. But, after the first batch for the S command the last command should be S and not M. It says it's M so it wrongly makes the first control point coincident to the current point. But, the first batch was an S command and now the unstated control point is the smooth reflection point, and it whiffs.

**Comment by tatarize** [comment]
Path 20 in the test routine also fails but might not be worth fixing. It exists back to svg.path and is actually something I had to go and check the XBNF to be sure was a even a thing:

M200,120 h-25 a25,25 0 1125,25 z

That's weird as heck. The flags are literally 1 1 they are by definition, 1 character of 0 or 1 and require no whitespace or comma. So literally they qualify there as 1125,25 is according to the XBNF unambiguously 1 1 25 25. Reported to regebro/svg.path#53
